name: Build, Push Container image to DockerHub

on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: "clamav-rest"

  REGISTRY_USER: ajilaag
  REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest
      
    outputs:
      image_digest: ${{ steps.container_metadata.outputs.digest }}
      image_tags: ${{ steps.meta_dev.outputs.tags }}

    steps:
    - uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta_dev
      uses: docker/metadata-action@v4
      with:
        images: ajilaag/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value={{date 'YYYYMMDD'}}
          Type=raw,value=latest,enable={{is_default_branch}}


    - name: Build and push to DockerHub
      id: container_metadata
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta_dev.outputs.tags }}
        labels: ${{ steps.meta_dev.outputs.labels }}
    
    - name: Add version tag
      id: tag_version
      uses: laputansoft/github-tag-action@v4.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: type=raw,value={{date 'YYYYMMDD'}}

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}