name: Build & Push Container image to DockerHub

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ajilaag/clamav-rest:$(date +'%Y%m%d')
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ajilaag
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to DockerHub
      run: docker push ajilaag/clamav-rest:$(date +'%Y%m%d')